name: Release

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.ACTOR }}
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changes
        id: is_main_ahead_of_latest_tag
        run: |
          number_of_diff_commits=$(git rev-list --count HEAD ^$(git describe --abbrev=0 --tags))
          echo $number_of_diff_commits
          has_changes=$(($number_of_diff_commits != 0 ? true : false))
          echo $has_changes
          echo has_changes=$has_changes >> $GITHUB_OUTPUT;

      - name: Get Previous Version
        id: get_previous_version
        if: steps.is_main_ahead_of_latest_tag.outputs.has_changes == '0'
        run: |
          previous_tag=$(git describe --abbrev=0 --tags)
          echo previous_tag=$previous_tag >> $GITHUB_OUTPUT;

      - name: Get New Version
        id: get_new_version
        if: steps.is_main_ahead_of_latest_tag.outputs.has_changes == '0'
        run: |
          previous_tag=${{ steps.get_previous_version.outputs.previous_tag }}
          version_number=$(echo "$previous_tag" | sed 's/v//')
          IFS='.' read -ra version_parts <<< "$version_number"
          version_parts[-1]=$((version_parts[-1]+1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo $previous_tag
          echo $new_version
          echo previous_tag=$previous_tag >> $GITHUB_OUTPUT;
          echo tag=$new_version >> $GITHUB_OUTPUT;

      - name: Create Release
        id: create_release
        if: steps.is_main_ahead_of_latest_tag.outputs.has_changes == '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          previous_tag=${{ steps.get_previous_version.outputs.previous_tag }}
          echo $previous_tag
          gh release create v${{ steps.get_new_version.outputs.tag }} \
          --target ${{ github.ref_name }} \
          --generate-notes --notes-start-tag "${previous_tag}"

      - name: Setup JDK
        if: steps.is_main_ahead_of_latest_tag.outputs.has_changes == '0'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Publish
        if: steps.is_main_ahead_of_latest_tag.outputs.has_changes == '0'
        env:
          PACKAGE_VERSION: ${{ steps.get_new_version.outputs.tag }}
        run: |
          echo PACKAGE_VERSION=$PACKAGE_VERSION
          ./gradlew publish
