name: Release
on:
  release:
    types: [ published ]

jobs:
  publish-package:
    name: Publish Github Package
    runs-on: ubuntu-latest
    env:
      GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.ACTOR }}
    if: github.event_name == 'release'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu'
            java-version: '17'
      - name: Publish
        run: ./gradlew assemble publish
